parameters:
#    infocorp_team.example.class: Infocorp\Bundle\TeamBundle\Example

services:
#    infocorp_team.example:
#        class: %infocorp_team.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
