services:
    sonata.admin.team:
        class: Infocorp\Bundle\TeamBundle\Admin\TeamAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Times, label: "Times"}
        arguments:
            - ~
            - Infocorp\Bundle\TeamBundle\Entity\Team 
            - 'SonataAdminBundle:CRUD'